version: '3.6'
# https://docs.docker.com/compose/

services:
  smart-brain-api:
    container_name: backend
    # image: node:carbon-alpine
    # builds from Dockerfile:
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    # referenced in server.js
    environment:
      POSTGRES_URI: postgres://clare:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
  # postgres
  postgres:
    environment:
      POSTGRES_USER: clare
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres #name of service
    build: ./postgres
    ports:
      - "5432:5432"

  # redis
  redis:
    image: redis
    ports:
      - "6379:6379"
