version: '3.6'
# https://docs.docker.com/compose/

services:
  smart-brain-api:
    container_name: backend
    # image: node:carbon-alpine
    # builds from Dockerfile:
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
